#!/bin/vbash

# IPv4 Forward Filter Rules

set firewall ipv4 forward filter default-action 'accept'
set firewall ipv4 forward filter rule 1 action 'accept'
set firewall ipv4 forward filter rule 1 state 'established'
set firewall ipv4 forward filter rule 2 action 'drop'
set firewall ipv4 forward filter rule 2 state 'invalid'
set firewall ipv4 forward filter rule 3 action 'accept'
set firewall ipv4 forward filter rule 3 state 'related'
set firewall ipv4 forward filter rule 101 action 'accept'
set firewall ipv4 forward filter rule 101 inbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 101 outbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 106 action 'jump'
set firewall ipv4 forward filter rule 106 inbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 106 jump-target 'guest-containers'
set firewall ipv4 forward filter rule 106 outbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 111 action 'jump'
set firewall ipv4 forward filter rule 111 inbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 111 jump-target 'lan-containers'
set firewall ipv4 forward filter rule 111 outbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 116 action 'jump'
set firewall ipv4 forward filter rule 116 inbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 116 jump-target 'servers-containers'
set firewall ipv4 forward filter rule 116 outbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 121 action 'jump'
set firewall ipv4 forward filter rule 121 inbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 121 jump-target 'trusted-containers'
set firewall ipv4 forward filter rule 121 outbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 126 action 'jump'
set firewall ipv4 forward filter rule 126 inbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 126 jump-target 'wan-containers'
set firewall ipv4 forward filter rule 126 outbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 131 action 'jump'
set firewall ipv4 forward filter rule 131 inbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 131 jump-target 'wireguard-containers'
set firewall ipv4 forward filter rule 131 outbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 136 action 'drop'
set firewall ipv4 forward filter rule 136 description 'zone_containers default-action'
set firewall ipv4 forward filter rule 136 outbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 141 action 'accept'
set firewall ipv4 forward filter rule 141 inbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 141 outbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 146 action 'jump'
set firewall ipv4 forward filter rule 146 inbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 146 jump-target 'containers-guest'
set firewall ipv4 forward filter rule 146 outbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 151 action 'jump'
set firewall ipv4 forward filter rule 151 inbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 151 jump-target 'lan-guest'
set firewall ipv4 forward filter rule 151 outbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 156 action 'jump'
set firewall ipv4 forward filter rule 156 inbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 156 jump-target 'servers-guest'
set firewall ipv4 forward filter rule 156 outbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 161 action 'jump'
set firewall ipv4 forward filter rule 161 inbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 161 jump-target 'trusted-guest'
set firewall ipv4 forward filter rule 161 outbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 166 action 'jump'
set firewall ipv4 forward filter rule 166 inbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 166 jump-target 'wan-guest'
set firewall ipv4 forward filter rule 166 outbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 171 action 'jump'
set firewall ipv4 forward filter rule 171 inbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 171 jump-target 'wireguard-guest'
set firewall ipv4 forward filter rule 171 outbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 176 action 'drop'
set firewall ipv4 forward filter rule 176 description 'zone_guest default-action'
set firewall ipv4 forward filter rule 176 outbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 181 action 'accept'
set firewall ipv4 forward filter rule 181 inbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 181 outbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 186 action 'jump'
set firewall ipv4 forward filter rule 186 inbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 186 jump-target 'containers-lan'
set firewall ipv4 forward filter rule 186 outbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 191 action 'jump'
set firewall ipv4 forward filter rule 191 inbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 191 jump-target 'guest-lan'
set firewall ipv4 forward filter rule 191 outbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 196 action 'jump'
set firewall ipv4 forward filter rule 196 inbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 196 jump-target 'servers-lan'
set firewall ipv4 forward filter rule 196 outbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 201 action 'jump'
set firewall ipv4 forward filter rule 201 inbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 201 jump-target 'trusted-lan'
set firewall ipv4 forward filter rule 201 outbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 206 action 'jump'
set firewall ipv4 forward filter rule 206 inbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 206 jump-target 'wan-lan'
set firewall ipv4 forward filter rule 206 outbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 211 action 'jump'
set firewall ipv4 forward filter rule 211 inbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 211 jump-target 'wireguard-lan'
set firewall ipv4 forward filter rule 211 outbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 216 action 'drop'
set firewall ipv4 forward filter rule 216 description 'zone_lan default-action'
set firewall ipv4 forward filter rule 216 outbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 221 action 'accept'
set firewall ipv4 forward filter rule 221 inbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 221 outbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 226 action 'jump'
set firewall ipv4 forward filter rule 226 inbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 226 jump-target 'containers-servers'
set firewall ipv4 forward filter rule 226 outbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 231 action 'jump'
set firewall ipv4 forward filter rule 231 inbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 231 jump-target 'guest-servers'
set firewall ipv4 forward filter rule 231 outbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 236 action 'jump'
set firewall ipv4 forward filter rule 236 inbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 236 jump-target 'lan-servers'
set firewall ipv4 forward filter rule 236 outbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 241 action 'jump'
set firewall ipv4 forward filter rule 241 inbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 241 jump-target 'trusted-servers'
set firewall ipv4 forward filter rule 241 outbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 246 action 'jump'
set firewall ipv4 forward filter rule 246 inbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 246 jump-target 'wan-servers'
set firewall ipv4 forward filter rule 246 outbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 251 action 'jump'
set firewall ipv4 forward filter rule 251 inbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 251 jump-target 'wireguard-servers'
set firewall ipv4 forward filter rule 251 outbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 256 action 'drop'
set firewall ipv4 forward filter rule 256 description 'zone_servers default-action'
set firewall ipv4 forward filter rule 256 outbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 261 action 'accept'
set firewall ipv4 forward filter rule 261 inbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 261 outbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 266 action 'jump'
set firewall ipv4 forward filter rule 266 inbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 266 jump-target 'containers-trusted'
set firewall ipv4 forward filter rule 266 outbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 271 action 'jump'
set firewall ipv4 forward filter rule 271 inbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 271 jump-target 'guest-trusted'
set firewall ipv4 forward filter rule 271 outbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 276 action 'jump'
set firewall ipv4 forward filter rule 276 inbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 276 jump-target 'lan-trusted'
set firewall ipv4 forward filter rule 276 outbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 281 action 'jump'
set firewall ipv4 forward filter rule 281 inbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 281 jump-target 'servers-trusted'
set firewall ipv4 forward filter rule 281 outbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 286 action 'jump'
set firewall ipv4 forward filter rule 286 inbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 286 jump-target 'wan-trusted'
set firewall ipv4 forward filter rule 286 outbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 291 action 'jump'
set firewall ipv4 forward filter rule 291 inbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 291 jump-target 'wireguard-trusted'
set firewall ipv4 forward filter rule 291 outbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 296 action 'drop'
set firewall ipv4 forward filter rule 296 description 'zone_trusted default-action'
set firewall ipv4 forward filter rule 296 outbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 301 action 'accept'
set firewall ipv4 forward filter rule 301 inbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 301 outbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 306 action 'jump'
set firewall ipv4 forward filter rule 306 inbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 306 jump-target 'containers-wan'
set firewall ipv4 forward filter rule 306 outbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 311 action 'jump'
set firewall ipv4 forward filter rule 311 inbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 311 jump-target 'guest-wan'
set firewall ipv4 forward filter rule 311 outbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 316 action 'jump'
set firewall ipv4 forward filter rule 316 inbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 316 jump-target 'lan-wan'
set firewall ipv4 forward filter rule 316 outbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 321 action 'jump'
set firewall ipv4 forward filter rule 321 inbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 321 jump-target 'servers-wan'
set firewall ipv4 forward filter rule 321 outbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 326 action 'jump'
set firewall ipv4 forward filter rule 326 inbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 326 jump-target 'trusted-wan'
set firewall ipv4 forward filter rule 326 outbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 331 action 'jump'
set firewall ipv4 forward filter rule 331 inbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 331 jump-target 'wireguard-wan'
set firewall ipv4 forward filter rule 331 outbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 336 action 'drop'
set firewall ipv4 forward filter rule 336 description 'zone_wan default-action'
set firewall ipv4 forward filter rule 336 outbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 341 action 'accept'
set firewall ipv4 forward filter rule 341 inbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 341 outbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 346 action 'jump'
set firewall ipv4 forward filter rule 346 inbound-interface group 'IG_containers'
set firewall ipv4 forward filter rule 346 jump-target 'containers-wireguard'
set firewall ipv4 forward filter rule 346 outbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 351 action 'jump'
set firewall ipv4 forward filter rule 351 inbound-interface group 'IG_guest'
set firewall ipv4 forward filter rule 351 jump-target 'guest-wireguard'
set firewall ipv4 forward filter rule 351 outbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 356 action 'jump'
set firewall ipv4 forward filter rule 356 inbound-interface group 'IG_lan'
set firewall ipv4 forward filter rule 356 jump-target 'lan-wireguard'
set firewall ipv4 forward filter rule 356 outbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 361 action 'jump'
set firewall ipv4 forward filter rule 361 inbound-interface group 'IG_servers'
set firewall ipv4 forward filter rule 361 jump-target 'servers-wireguard'
set firewall ipv4 forward filter rule 361 outbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 366 action 'jump'
set firewall ipv4 forward filter rule 366 inbound-interface group 'IG_trusted'
set firewall ipv4 forward filter rule 366 jump-target 'trusted-wireguard'
set firewall ipv4 forward filter rule 366 outbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 371 action 'jump'
set firewall ipv4 forward filter rule 371 inbound-interface group 'IG_wan'
set firewall ipv4 forward filter rule 371 jump-target 'wan-wireguard'
set firewall ipv4 forward filter rule 371 outbound-interface group 'IG_wireguard'
set firewall ipv4 forward filter rule 376 action 'drop'
set firewall ipv4 forward filter rule 376 description 'zone_wireguard default-action'
set firewall ipv4 forward filter rule 376 outbound-interface group 'IG_wireguard'

# IPv4 Input Filter Rules

set firewall ipv4 input filter default-action 'accept'
set firewall ipv4 input filter rule 1 action 'accept'
set firewall ipv4 input filter rule 1 state 'established'
set firewall ipv4 input filter rule 2 action 'drop'
set firewall ipv4 input filter rule 2 state 'invalid'
set firewall ipv4 input filter rule 3 action 'accept'
set firewall ipv4 input filter rule 3 state 'related'
set firewall ipv4 input filter rule 101 action 'jump'
set firewall ipv4 input filter rule 101 inbound-interface group 'IG_containers'
set firewall ipv4 input filter rule 101 jump-target 'containers-local'
set firewall ipv4 input filter rule 106 action 'jump'
set firewall ipv4 input filter rule 106 inbound-interface group 'IG_guest'
set firewall ipv4 input filter rule 106 jump-target 'guest-local'
set firewall ipv4 input filter rule 111 action 'jump'
set firewall ipv4 input filter rule 111 inbound-interface group 'IG_lan'
set firewall ipv4 input filter rule 111 jump-target 'lan-local'
set firewall ipv4 input filter rule 116 action 'jump'
set firewall ipv4 input filter rule 116 inbound-interface group 'IG_servers'
set firewall ipv4 input filter rule 116 jump-target 'servers-local'
set firewall ipv4 input filter rule 121 action 'jump'
set firewall ipv4 input filter rule 121 inbound-interface group 'IG_trusted'
set firewall ipv4 input filter rule 121 jump-target 'trusted-local'
set firewall ipv4 input filter rule 126 action 'jump'
set firewall ipv4 input filter rule 126 inbound-interface group 'IG_wan'
set firewall ipv4 input filter rule 126 jump-target 'wan-local'
set firewall ipv4 input filter rule 131 action 'jump'
set firewall ipv4 input filter rule 131 inbound-interface group 'IG_wireguard'
set firewall ipv4 input filter rule 131 jump-target 'wireguard-local'
set firewall ipv4 input filter rule 136 action 'drop'

# IPv4 Names

set firewall ipv4 name containers-guest default-action 'accept'
set firewall ipv4 name containers-guest description 'From CONTAINERS to GUEST'
set firewall ipv4 name containers-lan default-action 'accept'
set firewall ipv4 name containers-lan description 'From CONTAINERS to LAN'
set firewall ipv4 name containers-local default-action 'accept'
set firewall ipv4 name containers-local description 'From CONTAINERS to LOCAL'
set firewall ipv4 name containers-servers default-action 'accept'
set firewall ipv4 name containers-servers description 'From CONTAINERS to SERVERS'
set firewall ipv4 name containers-trusted default-action 'accept'
set firewall ipv4 name containers-trusted description 'From CONTAINERS to TRUSTED'
set firewall ipv4 name containers-wan default-action 'accept'
set firewall ipv4 name containers-wan description 'From CONTAINERS to WAN'
set firewall ipv4 name containers-wireguard default-action 'accept'
set firewall ipv4 name containers-wireguard description 'From CONTAINERS to WIREGUARD'
set firewall ipv4 name guest-containers default-action 'drop'
set firewall ipv4 name guest-containers description 'From GUEST to CONTAINERS'
set firewall ipv4 name guest-containers rule 100 action 'accept'
set firewall ipv4 name guest-containers rule 100 description 'Rule: accept_dns'
set firewall ipv4 name guest-containers rule 100 destination port 'domain,domain-s'
set firewall ipv4 name guest-containers rule 100 protocol 'tcp_udp'
set firewall ipv4 name guest-lan default-action 'drop'
set firewall ipv4 name guest-lan description 'From GUEST to LAN'
set firewall ipv4 name guest-local default-action 'drop'
set firewall ipv4 name guest-local description 'From GUEST to LOCAL'
set firewall ipv4 name guest-servers default-action 'drop'
set firewall ipv4 name guest-servers description 'From GUEST to SERVERS'
set firewall ipv4 name guest-trusted default-action 'drop'
set firewall ipv4 name guest-trusted description 'From GUEST to TRUSTED'
set firewall ipv4 name guest-wan default-action 'accept'
set firewall ipv4 name guest-wan description 'From GUEST to WAN'
set firewall ipv4 name guest-wireguard default-action 'drop'
set firewall ipv4 name guest-wireguard description 'From GUEST to WIREGUARD'
set firewall ipv4 name lan-containers default-action 'accept'
set firewall ipv4 name lan-containers description 'From LAN to CONTAINERS'
set firewall ipv4 name lan-guest default-action 'accept'
set firewall ipv4 name lan-guest description 'From LAN to GUEST'
set firewall ipv4 name lan-local default-action 'accept'
set firewall ipv4 name lan-local description 'From LAN to LOCAL'
set firewall ipv4 name lan-servers default-action 'accept'
set firewall ipv4 name lan-servers description 'From LAN to SERVERS'
set firewall ipv4 name lan-trusted default-action 'accept'
set firewall ipv4 name lan-trusted description 'From LAN to TRUSTED'
set firewall ipv4 name lan-wan default-action 'accept'
set firewall ipv4 name lan-wan description 'From LAN to WAN'
set firewall ipv4 name lan-wireguard default-action 'accept'
set firewall ipv4 name lan-wireguard description 'From LAN to WIREGUARD'
set firewall ipv4 name local-containers default-action 'accept'
set firewall ipv4 name local-containers description 'From LOCAL to CONTAINERS'
set firewall ipv4 name local-guest default-action 'accept'
set firewall ipv4 name local-guest description 'From LOCAL to GUEST'
set firewall ipv4 name local-lan default-action 'accept'
set firewall ipv4 name local-lan description 'From LOCAL to LAN'
set firewall ipv4 name local-servers default-action 'accept'
set firewall ipv4 name local-servers description 'From LOCAL to SERVERS'
set firewall ipv4 name local-trusted default-action 'accept'
set firewall ipv4 name local-trusted description 'From LOCAL to TRUSTED'
set firewall ipv4 name local-wan default-action 'accept'
set firewall ipv4 name local-wan description 'From LOCAL to WAN'
set firewall ipv4 name local-wireguard default-action 'accept'
set firewall ipv4 name local-wireguard description 'From LOCAL to WIREGUARD'
set firewall ipv4 name servers-containers default-action 'accept'
set firewall ipv4 name servers-containers description 'From SERVERS to CONTAINERS'
set firewall ipv4 name servers-guest default-action 'accept'
set firewall ipv4 name servers-guest description 'From SERVERS to GUEST'
set firewall ipv4 name servers-lan default-action 'accept'
set firewall ipv4 name servers-lan description 'From SERVERS to LAN'
set firewall ipv4 name servers-local default-action 'accept'
set firewall ipv4 name servers-local description 'From SERVERS to LOCAL'
set firewall ipv4 name servers-trusted default-action 'accept'
set firewall ipv4 name servers-trusted description 'From SERVERS to TRUSTED'
set firewall ipv4 name servers-wan default-action 'accept'
set firewall ipv4 name servers-wan description 'From SERVERS to WAN'
set firewall ipv4 name servers-wireguard default-action 'accept'
set firewall ipv4 name servers-wireguard description 'From SERVERS to WIREGUARD'
set firewall ipv4 name trusted-containers default-action 'accept'
set firewall ipv4 name trusted-containers description 'From TRUSTED to CONTAINERS'
set firewall ipv4 name trusted-guest default-action 'accept'
set firewall ipv4 name trusted-guest description 'From TRUSTED to GUEST'
set firewall ipv4 name trusted-lan default-action 'accept'
set firewall ipv4 name trusted-lan description 'From TRUSTED to LAN'
set firewall ipv4 name trusted-local default-action 'accept'
set firewall ipv4 name trusted-local description 'From TRUSTED to LOCAL'
set firewall ipv4 name trusted-servers default-action 'accept'
set firewall ipv4 name trusted-servers description 'From TRUSTED to SERVERS'
set firewall ipv4 name trusted-wan default-action 'accept'
set firewall ipv4 name trusted-wan description 'From TRUSTED to WAN'
set firewall ipv4 name trusted-wireguard default-action 'accept'
set firewall ipv4 name trusted-wireguard description 'From TRUSTED to WIREGUARD'
set firewall ipv4 name wan-containers default-action 'drop'
set firewall ipv4 name wan-containers description 'From WAN to CONTAINERS'
set firewall ipv4 name wan-containers enable-default-log
set firewall ipv4 name wan-guest default-action 'drop'
set firewall ipv4 name wan-guest description 'From WAN to GUEST'
set firewall ipv4 name wan-guest enable-default-log
set firewall ipv4 name wan-lan default-action 'drop'
set firewall ipv4 name wan-lan description 'From WAN to LAN'
set firewall ipv4 name wan-lan enable-default-log
set firewall ipv4 name wan-local default-action 'drop'
set firewall ipv4 name wan-local description 'From WAN to LOCAL'
set firewall ipv4 name wan-local enable-default-log
set firewall ipv4 name wan-local rule 400 action 'accept'
set firewall ipv4 name wan-local rule 400 description 'Rule: Accept Wireguard'
set firewall ipv4 name wan-local rule 400 destination port '51820'
set firewall ipv4 name wan-local rule 400 protocol 'udp'
set firewall ipv4 name wan-servers default-action 'drop'
set firewall ipv4 name wan-servers description 'From WAN to SERVERS'
set firewall ipv4 name wan-servers enable-default-log
set firewall ipv4 name wan-servers rule 301 action 'accept'
set firewall ipv4 name wan-servers rule 301 description 'Plexk3s - Allow incoming traffic on port 32400 to 10.0.30.32'
set firewall ipv4 name wan-servers rule 301 destination group address-group 'k8s-ingress'
set firewall ipv4 name wan-servers rule 301 destination port '32400'
set firewall ipv4 name wan-servers rule 301 protocol 'tcp'
set firewall ipv4 name wan-servers rule 400 action 'accept'
set firewall ipv4 name wan-servers rule 400 description 'Rule: Accept ingress from Cloudflare'
set firewall ipv4 name wan-servers rule 400 destination group address-group 'k8s-ingress'
set firewall ipv4 name wan-servers rule 400 destination port 'http,https'
set firewall ipv4 name wan-servers rule 400 protocol 'tcp'
set firewall ipv4 name wan-servers rule 400 source group network-group 'cloudflare-networks-v4'
set firewall ipv4 name wan-trusted default-action 'drop'
set firewall ipv4 name wan-trusted description 'From WAN to TRUSTED'
set firewall ipv4 name wan-trusted enable-default-log
set firewall ipv4 name wan-wireguard default-action 'drop'
set firewall ipv4 name wan-wireguard description 'From WAN to WIREGUARD'
set firewall ipv4 name wan-wireguard enable-default-log
set firewall ipv4 name wireguard-containers default-action 'accept'
set firewall ipv4 name wireguard-containers description 'From WIREGUARD to CONTAINERS'
set firewall ipv4 name wireguard-guest default-action 'accept'
set firewall ipv4 name wireguard-guest description 'From WIREGUARD to GUEST'
set firewall ipv4 name wireguard-lan default-action 'accept'
set firewall ipv4 name wireguard-lan description 'From WIREGUARD to LAN'
set firewall ipv4 name wireguard-local default-action 'accept'
set firewall ipv4 name wireguard-local description 'From WIREGUARD to LOCAL'
set firewall ipv4 name wireguard-servers default-action 'accept'
set firewall ipv4 name wireguard-servers description 'From WIREGUARD to SERVERS'
set firewall ipv4 name wireguard-trusted default-action 'accept'
set firewall ipv4 name wireguard-trusted description 'From WIREGUARD to TRUSTED'
set firewall ipv4 name wireguard-wan default-action 'accept'
set firewall ipv4 name wireguard-wan description 'From WIREGUARD to WAN'

# IPv4 Output Filter Rules

set firewall ipv4 output filter default-action 'accept'
set firewall ipv4 output filter rule 1 action 'accept'
set firewall ipv4 output filter rule 1 state 'established'
set firewall ipv4 output filter rule 2 action 'drop'
set firewall ipv4 output filter rule 2 state 'invalid'
set firewall ipv4 output filter rule 3 action 'accept'
set firewall ipv4 output filter rule 3 state 'related'
set firewall ipv4 output filter rule 101 action 'jump'
set firewall ipv4 output filter rule 101 jump-target 'local-containers'
set firewall ipv4 output filter rule 101 outbound-interface group 'IG_containers'
set firewall ipv4 output filter rule 106 action 'jump'
set firewall ipv4 output filter rule 106 jump-target 'local-guest'
set firewall ipv4 output filter rule 106 outbound-interface group 'IG_guest'
set firewall ipv4 output filter rule 111 action 'jump'
set firewall ipv4 output filter rule 111 jump-target 'local-lan'
set firewall ipv4 output filter rule 111 outbound-interface group 'IG_lan'
set firewall ipv4 output filter rule 116 action 'jump'
set firewall ipv4 output filter rule 116 jump-target 'local-servers'
set firewall ipv4 output filter rule 116 outbound-interface group 'IG_servers'
set firewall ipv4 output filter rule 121 action 'jump'
set firewall ipv4 output filter rule 121 jump-target 'local-trusted'
set firewall ipv4 output filter rule 121 outbound-interface group 'IG_trusted'
set firewall ipv4 output filter rule 126 action 'jump'
set firewall ipv4 output filter rule 126 jump-target 'local-wan'
set firewall ipv4 output filter rule 126 outbound-interface group 'IG_wan'
set firewall ipv4 output filter rule 131 action 'jump'
set firewall ipv4 output filter rule 131 jump-target 'local-wireguard'
set firewall ipv4 output filter rule 131 outbound-interface group 'IG_wireguard'
set firewall ipv4 output filter rule 136 action 'drop'