#!/bin/vbash

# IPv6 Forward Filter Rules

set firewall ipv6 forward filter default-action 'accept'
set firewall ipv6 forward filter rule 1 action 'accept'
set firewall ipv6 forward filter rule 1 state 'established'
set firewall ipv6 forward filter rule 2 action 'drop'
set firewall ipv6 forward filter rule 2 state 'invalid'
set firewall ipv6 forward filter rule 3 action 'accept'
set firewall ipv6 forward filter rule 3 state 'related'
set firewall ipv6 forward filter rule 101 action 'accept'
set firewall ipv6 forward filter rule 101 inbound-interface group 'IG_containers'
set firewall ipv6 forward filter rule 101 outbound-interface group 'IG_containers'
set firewall ipv6 forward filter rule 106 action 'drop'
set firewall ipv6 forward filter rule 106 description 'zone_containers default-action'
set firewall ipv6 forward filter rule 106 outbound-interface group 'IG_containers'
set firewall ipv6 forward filter rule 111 action 'accept'
set firewall ipv6 forward filter rule 111 inbound-interface group 'IG_guest'
set firewall ipv6 forward filter rule 111 outbound-interface group 'IG_guest'
set firewall ipv6 forward filter rule 116 action 'drop'
set firewall ipv6 forward filter rule 116 description 'zone_guest default-action'
set firewall ipv6 forward filter rule 116 outbound-interface group 'IG_guest'
set firewall ipv6 forward filter rule 121 action 'accept'
set firewall ipv6 forward filter rule 121 inbound-interface group 'IG_lan'
set firewall ipv6 forward filter rule 121 outbound-interface group 'IG_lan'
set firewall ipv6 forward filter rule 126 action 'drop'
set firewall ipv6 forward filter rule 126 description 'zone_lan default-action'
set firewall ipv6 forward filter rule 126 outbound-interface group 'IG_lan'
set firewall ipv6 forward filter rule 131 action 'accept'
set firewall ipv6 forward filter rule 131 inbound-interface group 'IG_servers'
set firewall ipv6 forward filter rule 131 outbound-interface group 'IG_servers'
set firewall ipv6 forward filter rule 136 action 'drop'
set firewall ipv6 forward filter rule 136 description 'zone_servers default-action'
set firewall ipv6 forward filter rule 136 outbound-interface group 'IG_servers'
set firewall ipv6 forward filter rule 141 action 'accept'
set firewall ipv6 forward filter rule 141 inbound-interface group 'IG_trusted'
set firewall ipv6 forward filter rule 141 outbound-interface group 'IG_trusted'
set firewall ipv6 forward filter rule 146 action 'drop'
set firewall ipv6 forward filter rule 146 description 'zone_trusted default-action'
set firewall ipv6 forward filter rule 146 outbound-interface group 'IG_trusted'
set firewall ipv6 forward filter rule 151 action 'accept'
set firewall ipv6 forward filter rule 151 inbound-interface group 'IG_wan'
set firewall ipv6 forward filter rule 151 outbound-interface group 'IG_wan'
set firewall ipv6 forward filter rule 156 action 'drop'
set firewall ipv6 forward filter rule 156 description 'zone_wan default-action'
set firewall ipv6 forward filter rule 156 outbound-interface group 'IG_wan'
set firewall ipv6 forward filter rule 161 action 'accept'
set firewall ipv6 forward filter rule 161 inbound-interface group 'IG_wireguard'
set firewall ipv6 forward filter rule 161 outbound-interface group 'IG_wireguard'
set firewall ipv6 forward filter rule 166 action 'drop'
set firewall ipv6 forward filter rule 166 description 'zone_wireguard default-action'
set firewall ipv6 forward filter rule 166 outbound-interface group 'IG_wireguard'

# IPv6 Input Filters Rules

set firewall ipv6 input filter default-action 'accept'
set firewall ipv6 input filter rule 1 action 'accept'
set firewall ipv6 input filter rule 1 state 'established'
set firewall ipv6 input filter rule 2 action 'drop'
set firewall ipv6 input filter rule 2 state 'invalid'
set firewall ipv6 input filter rule 3 action 'accept'
set firewall ipv6 input filter rule 3 state 'related'
set firewall ipv6 input filter rule 101 action 'drop'

# IPv6 Output Filters Rules

set firewall ipv6 output filter default-action 'accept'
set firewall ipv6 output filter rule 1 action 'accept'
set firewall ipv6 output filter rule 1 state 'established'
set firewall ipv6 output filter rule 2 action 'drop'
set firewall ipv6 output filter rule 2 state 'invalid'
set firewall ipv6 output filter rule 3 action 'accept'
set firewall ipv6 output filter rule 3 state 'related'
set firewall ipv6 output filter rule 101 action 'drop'